config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: 'pages#home'
    get 'about', to: 'pages#about'
    resources :contacts, only: :create
    get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  # Contact for validations
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  # GET request to /contact-us
  # Show new contact form
  def new
    @contact = Contact.new
  end
  
  # POST request /contacts
  def create
    # Mass assignment of form fields into Contact object
    @contact = Contact.new(contact_params)
    # Save the Contact object to database
    if @contact.save
      # Store form fields via paramaters into variabls
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      # Plug variables into Contact Mailer
      # email method and send mail
      ContactMailer.contact_email(name, email, body).deliver
      # Store success message in flash hash
      # and redirect to the new action
      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      # If Contact object does not save,
      # store errors in flash hash,
      # and redirect to the new action
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end
  
  private
  # To collect data from form, we need to use
  # strong parameters and whitelist the form fields
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  #GET request for / which is our home page
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end
  
  
  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class = "container">
  <div class="row">
    <h3 class = "text-center">Contact Us</h3>
    
    <div class="col-md-4 col-md-offset-4">
      <div class="well">
        <%= form_for @contact do |f| %>
          <div class = "form-group">
            <%= f.label :name%>
            <%=f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class = "form-group">
            <%= f.label :email%>
            <%=f.text_field :email, class: 'form-control' %>
          </div>
          
          <div class = "form-group">
            <%= f.label :comments%>
            <%=f.text_area :comments, class: 'form-control' %>
          </div>
          
          <%= f.submit 'Submit', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https:/js.stripe.com/v2/", type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-group"></i>
            DevMatch
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
            <% else %>
              <%= link_to "Log in", new_user_session_path, class: "btn btn-default navbar-btn" %>
            <% end %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact Us", new_contact_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <div class="container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    
    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
    <h1>About Page</h1>
    <p>We are DevMatch. A company focusing on creating an exclusive community 
    between entrepreneurs and developers.
    </p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
    <h1>Welcome to DevMatch.</h1>
    <h3>A membership site where entrepreneurs can meet developers.</h3>
</div>

<div class="container home-signup-links">
  <div class="rows">
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Basic Membership Link</h2>
        <h4>Sign up for free and get basic access to the community</h4>
        <br />
        <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg 
        btn-block' %>
      </div>
    </div>
    
    <div class="col-md-6">
      <div class ="well">
        <h2 class="text-center">Pro Membership Link</h2>
        <h4>Sign up for pro account for £10 per month and get access to the 
        community and contact information!</h4>
        <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-primary 
        btn-lg btn-block' %>
      </div>
    </div>
  </div>
</div>